In [43]:
import pandas as pd
import numpy as np
import json
import plotly.express as px
import seaborn as sns

In [19]:
df_group_census = pd.read_csv("eda_group_census_02.csv")
df_group_census.head()

,group,messages_sampled,messages_estimated,top_lang,top_lang_pct,en_pct,year_min,year_max,n_langs
0,gmane.linux.kernel,5117,255850,en,98.8,98.8,2002,2019,23
1,gmane.comp.kde.devel.bugs,3816,190800,en,81.8,81.8,2002,2019,25
2,gmane.linux.debian.devel.bugs.general,3033,151650,en,97.9,97.9,2002,2019,23
3,gmane.os.freebsd.devel.pkg-fallout,2349,117450,en,99.2,99.2,2013,2019,2
4,gmane.linux.gentoo.cvs,2036,101800,en,82.1,82.1,2003,2019,26

In [20]:
df_group_census.size

86310

In [21]:
df_group_census.describe()

,messages_sampled,messages_estimated,top_lang_pct,en_pct,year_min,year_max,n_langs
count,9590.000000,9590.000000,9590.000000,9590.000000,9590.000000,9590.000000,9590.000000
mean,30.433264,1521.663191,95.601908,87.323285,2006.818978,2012.311053,1.674453
std,113.608034,5680.401693,10.812406,28.778911,4.172120,5.033242,1.687731
min,1.000000,50.000000,20.000000,0.000000,1991.000000,1995.000000,1.000000
25%,2.000000,100.000000,97.625000,94.900000,2003.000000,2008.000000,1.000000
50%,7.000000,350.000000,100.000000,100.000000,2006.000000,2013.000000,1.000000
75%,22.000000,1100.000000,100.000000,100.000000,2010.000000,2017.000000,2.000000
max,5117.000000,255850.000000,100.000000,100.000000,2019.000000,2019.000000,26.000000

In [31]:
df_group_census.loc[0:20]

,group,messages_sampled,messages_estimated,top_lang,top_lang_pct,en_pct,year_min,year_max,n_langs
0,gmane.linux.kernel,5117,255850,en,98.8,98.8,2002,2019,23
1,gmane.comp.kde.devel.bugs,3816,190800,en,81.8,81.8,2002,2019,25
2,gmane.linux.debian.devel.bugs.general,3033,151650,en,97.9,97.9,2002,2019,23
3,gmane.os.freebsd.devel.pkg-fallout,2349,117450,en,99.2,99.2,2013,2019,2
4,gmane.linux.gentoo.cvs,2036,101800,en,82.1,82.1,2003,2019,26
5,gmane.comp.python.general,1391,69550,en,98.6,98.6,1999,2019,10
6,gmane.linux.ports.arm.kernel,1371,68550,en,98.7,98.7,2002,2019,15
7,gmane.linux.kernel.commits.head,1366,68300,en,96.6,96.6,2002,2018,14
8,gmane.comp.compilers.llvm.cvs,1213,60650,en,95.8,95.8,2005,2019,16
9,gmane.org.wikimedia.mediawiki.cvs,1211,60550,en,91.3,91.3,2004,2018,13
10,gmane.user-groups.linux.czech,1187,59350,cs,68.5,2.6,2004,2019,20
11,gmane.comp.gcc.bugs,1177,58850,en,80.5,80.5,2002,2019,21
12,gmane.comp.documentfoundation.libreoffice.bugs,1166,58300,en,81.0,81.0,2011,2019,13
13,gmane.comp.emulators.qemu,1156,57800,en,97.7,97.7,2004,2019,12
14,gmane.os.freebsd.devel.cvs,1141,57050,en,93.9,93.9,2002,2019,15
15,gmane.comp.web.chromium.bugs,1137,56850,en,99.4,99.4,2008,2013,5
16,gmane.comp.kde.bugs,1136,56800,en,85.8,85.8,2008,2011,13
17,gmane.linux.network,1136,56800,en,97.9,97.9,2002,2019,12
18,gmane.linux.debian.devel.bugs.rc,1101,55050,en,99.0,99.0,2003,2019,7
19,gmane.org.wikimedia.mediawiki.bugs,1038,51900,en,71.2,71.2,2004,2014,15
20,gmane.linux.debian.user,1036,51800,en,97.3,97.3,2002,2019,14

In [41]:
df_group_census[df_group_census.apply(lambda r: r.str.contains('python').any(), axis=1)]

,group,messages_sampled,messages_estimated,top_lang,top_lang_pct,en_pct,year_min,year_max,n_langs
5,gmane.comp.python.general,1391,69550,en,98.6,98.6,1999,2019,10
32,gmane.comp.python.bugs,752,37600,en,82.3,82.3,2000,2019,7
95,gmane.comp.python.django.user,372,18600,en,97.8,97.8,2005,2019,6
104,gmane.comp.python.django.scm,352,17600,en,93.2,93.2,2007,2019,12
120,gmane.comp.python.web2py,317,15850,en,96.5,96.5,2008,2019,8
...,...,...,...,...,...,...,...,...,...
9444,gmane.linux.debian.devel.python.py3porters,1,50,en,100.0,100.0,2015,2015,1
9477,gmane.comp.python.modeling,1,50,en,100.0,100.0,2004,2004,1
9567,gmane.comp.python.jobs,1,50,en,100.0,100.0,2009,2009,1
9568,gmane.comp.python.simpy.user,1,50,en,100.0,100.0,2014,2014,1
9569,gmane.comp.python.twisted.jabber,1,50,en,100.0,100.0,2009,2009,1

In [52]:
with open("eda_profile_01_python_devel.json", mode= "r") as f:
    data = json.load(f)

print(data)
df_python_devel = pd.DataFrame.from_dict(data)
df_python_devel.head()

{'meta': {'mode': 'profile', 'files': 1, 'sample_rate': 1, 'max_per_file': None, 'full_scan': True, 'groups_filter': ['gmane.comp.python.devel'], 'lang_filter': None, 'email_segment_labels': ['paragraph', 'section_heading'], 'pattern_set_version': '0.2'}, 'groups': [{'group': 'gmane.comp.python.devel', 'messages_sampled': 16309, 'messages_estimated': 16309, 'unique_authors': 1544, 'msgs_per_author': 10.6, 'en_pct': 99.2, 'year_min': 1999, 'year_max': 2019, 'reply_pct': 78.5, 'thread_resolution_pct': 0.5, 'bot_from_pct': 0.0, 'templated_subject_pct': 0.4, 'machine_segment_pct': 24.1, 'paragraph_segment_pct': 28.5, 'kept_segments_per_msg': 2.37, 'kept_span_valid_pct': 100.0, 'utf8_bytes_doc_pct': 15.6, 'est_text_units': 55032, 'est_text_units_scaled': 55032, 'est_annotatable_units_scaled': 52115, 'mean_chars_per_msg': 1605, 'nk_prescreen_pct': None}]}

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [ ]:
>